### PR TITLE
Created Python/Jupyter version of RMarkdown analysis

### PR DESCRIPTION
**Pull request by rgerkin**
I took the RMarkdown analysis and reimplemented it all in Python/Jupyter.  The goals were (1) to verify the analysis and (2) to give Python developers/analysts an entrypoint to this dataset when it is published.  The manuscript should note somewhere that this is available.

### CODE REVIEW

**Comment by rgerkin** [comment]
The work can be previewed at: https://github.com/rgerkin/GCCR001/blob/master/analysis/paper/analysis.ipynb
or:
https://nbviewer.jupyter.org/github/rgerkin/GCCR001/blob/master/analysis/paper/analysis.ipynb

**Comment by kwcooper** [comment]
I'm 100% for it. I suppose the only possible issue I can think of may be that someone might see the python code and think that is what is used in the paper, but I think your jupyter header is clear enough that this will be a non-issue.

**Comment by rgerkin** [comment]
@kwcooper Yes, and you can further modify the header as needed if it can reduce addition confusion (or even rename the file).  It could even have a link to the RMarkdown code. 

When the RMarkdown file is 100% finished (and the paper submitted), I'll revisit to change the order of analyses, figure labels, etc. to match as closely as possible.

**Comment by kwcooper** [comment]
All sounds great! 

Thank you again for getting the ball rolling on this! Looking forward to see what may come from it.

**Pull request merged**
